Repository geekflyer/aptos-core, pull requests merged in 2022-06, with the labels that each got.

#5 add feature 1
  change1.MD
Labels: mergequeue

#6 add feature 2
  change2.MD
Labels: mergequeue

#9 feature
  .github/workflows/lint-test.yaml
  features.MD
Labels: mergequeue

#12 feature
  .github/workflows/lint-test.yaml
  features.MD
Labels: mergequeue

#14 feature
  .github/workflows/lint-test.yaml
Labels: mergequeue

#16 stuff
  featuresnew.MD
Labels: mergequeue

#20 ci(Mergify): configuration update
  .mergify.yml
Labels: mergequeue

#22 stuff
  .mergify.yml
  featuresnewnew.MD
Labels: automerge

#23 stuff
  feature10.MD
Labels: automerge

#24 stuff
  feature11.MD
Labels: automerge

#25 stuff
  feature12.MD
Labels: automerge

#26 stuff
  .mergify.yml
Labels: automerge

#27 stuff
  feature13.MD
Labels: automerge

#29 foo
  feature15.MD
Labels: automerge

#35 Update change2.MD
  change2.MD
Labels: automerge

#34 Update featuresnewnew.MD
  feature17.MD
Labels: automerge

#36 ci(Mergify): configuration update
  .mergify.yml
Labels: automerge

#39 thechange
  .github/workflows/lint-test.yaml
  feature1149.MD
  feature144149.MD
Labels: automerge

#42 7
  .github/workflows/lint-test.yaml
Labels: automerge

#43 foo
  .github/workflows/lint-test.yaml
  f1239.MD
Labels: automerge

#44 feature-3635
  .github/workflows/lint-test.yaml
  .mergify.yml
  feature-3635.md
Labels: automerge

#45 feature-16275
  .github/workflows/lint-test.yaml
  .kodiak.toml
  feature-16275.md
Labels: automerge, merge

#48 feature-24114
  feature-24114.md
Labels: merge

#50 feature-22257
  feature-22257.md
Labels: merge

#51 feature-30667
  .github/workflows/foo.json
  feature-30667.md
Labels: merge

#52 feature-21709
  feature-21709.md
Labels: merge

#53 feature-30271
  feature-30271.md
Labels: merge

#54 feature-11789
  feature-11789.md
Labels: merge

#55 feature-26624
  feature-26624.md
Labels: merge

#56 feature-22972
  feature-22972.md
Labels: merge

#57 feature-24340
  .github/workflows/lint-test.yaml
  feature-24340.md
Labels: merge

#58 feature-20802
  feature-20802.md
Labels: automerge

#65 feature-29989
  feature-29989.md
Labels: automerge
